[package]
name = "soleg-rust-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "^1.18"
solana-program = "^1.18"
solana-rpc-client = "^1.18"
solana-sdk = "^1.18"
spl-token = { version = "^4", features = ["no-entrypoint"] }
tokio = "1.35.1"
signature = "2.3.0-pre.4"